#!/usr/bin/env python


import rospy
#from std_msgs.msg import String
#from std_msgs.msg import Float32MultiArray
#from std_msgs.msg import Int16
#import serial
from array import array
import numpy as np
from numpy import nan
from matplotlib import pyplot as plt
import matplotlib.cm as cm
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.basemap import Basemap
from scipy.stats import multivariate_normal
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import WhiteKernel,RBF, ConstantKernel as C

def learn_map():
#    fname = input("Enter file name: ")
    num_lines = 0
    num_read=0
    num_lines_old = 0
#    lines_=[]
#    pos=np.array([])
#    util=np.array([])
#    pos=[]
#    util=[]
    X=[]
    f = open("system_load.txt", "r")
    for y in f:
    	x=y.split(',')
#	print(x)
	num_lines += 1
#	print num_lines
#	pos=np.array(pos)
#	util=np.array(util)
        if (x[1]!=nan):
#	    pos.append([(x[1]),(x[2])])
#	    util.append(x[3])
            X.append([(x[1]),(x[2]),x[3]])
#        if num_lines == 250:	   
#	    break

#        if (num_lines-num_lines_old) == 10:
##            pos = pos.reshape(-1, 1)
##            util = util.reshape(-1, 1)
#	    # Fit to data using Maximum Likelihood Estimation of the parameters
##	    gp.fit(pos, util)
#	    break

if __name__ == '__main__':
    try:
        learn_map()
        
    except rospy.ROSInterruptException:
        pass
